---
- name: Disable IPv6 with sysctl
  sysctl:
    name: '{{ item }}'
    value: "1"
    sysctl_set: yes
    state: absent
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
