---
- name: Populate Authorized Keys
  authorized_key:
    user: benr
    state: present
    key: "{{ lookup ('file', item ) }}"
  with_fileglob:
    - 'public_keys/*'

- name: Populate Additional Authroized Keys
  authorized_key:
    user: benr
    state: present
    key: "{{ item }}"
  with_items: "{{ extra_authorized_keys | default([]) }}"

- name: ssh config file
  template: src=sshd_config dest=/etc/ssh/sshd_config
  notify: reload sshd

- openssh_keypair:
    path: /home/benr/.ssh/id_rsa
    owner: benr
    group: benr

