---
- name: Install Required Packages
  apt:
    pkg:
      - weechat

- name: Create .weechat directory
  file:
    path: /home/benr/.weechat
    state: directory
    mode: '0755'

- name: Install weechat irc config
  copy:
    src: irc.conf
    dest: /home/benr/.weechat/irc.conf

- name: Install weechat sec config
  copy:
    src: sec.conf
    dest: /home/benr/.weechat/sec.conf
