---
- name: Install Git
  apt:
    name:
      - git
    state: latest
    update_cache: True
    cache_valid_time: 86400
  become: true


- name: Clone doorbell github repo
  git:
    repo: https://github.com/bl-robinson/doorbell.git
    dest: /home/benr/doorbell
    clone: yes
    update: yes

- name: Install python deps from requirements.txt
  pip:
    requirements: /home/benr/doorbell/requirements.txt
  become: true

- name: Copy systemd service file into place
  copy:
    src: doorbell.service
    dest: /etc/systemd/system/doorbell.service

- name: Start doorbell service
  systemd:
    state: started
    name: doorbell
    enabled: True

- name: Setup Cleanup cron
  cron:
    name: "Cleanup Old Video Files"
    minute: "0"
    hour: "*"
    job: "find /mnt/door-bell -mtime 1 -delete"
