---
- name: Install Git
  apt:
    name:
      - git
    state: latest
    update_cache: True
    cache_valid_time: 86400
  become: true

- name: Install Apt requirements
  apt:
    name:
      - pip
      - libssl-dev

- name: Copy systemd doorbell-cam service file into place
  copy:
    src: doorbell-cam.service
    dest: /etc/systemd/system/doorbell-cam.service
  notify:
    - daemon_reload

- name: Copy systemd doorbell-button service file into place
  copy:
    src: doorbell-button.service
    dest: /etc/systemd/system/doorbell-button.service
  notify:
    - daemon_reload

- name: Clone doorbell github repo
  git:
    repo: https://github.com/bl-robinson/doorbell.git
    dest: /home/benr/doorbell
    clone: yes
    update: yes
  notify:
    - restart_doorbell_cam
    - restart_doorbell_button

- name: Doorbell button config
  import_tasks: doorbell-button-config.yml
  when: "'doorbell' in inventory_hostname"

- name: Doorbell camera config
  import_tasks: doorbell-camera-config.yml
  when: "'front-door' in inventory_hostname"