---
- name: Install Common Utils
  apt:
    name:
      - mailutils
    state: latest
    update_cache: True
    cache_valid_time: 86400
  become: true

- name: Postfix
  import_tasks: postfix.yml

- name: opendkim
  import_tasks: opendkim.yml

- name: Dovecot
  import_tasks: dovecot.yml