--- 
    - name: Install Base Packages
      apt:
        pkg:
          - ca-certificates
          - apt-transport-https
        state: latest
        update_cache: True
        cache_valid_time: 86400

    - name: Unifi Apt Key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 06E85760C0A52C50

    - name: Unifi Apt Repo
      apt_repository: 
        repo: deb https://www.ui.com/downloads/unifi/debian stable ubiquiti
        state: present

    - name: Mongodb Apt Key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.0.asc
        state: present

    - name: Mongodb Apt Repo
      apt_repository: 
        repo: deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main
        state: present

    - name: Install Unifi
      apt:
        pkg:
          - unifi
        state: latest

  