--- 
    - name: Install Base Packages
      apt:
        pkg:
          - ca-certificates
          - apt-transport-https
          - multiarch-support
        state: latest
        update_cache: True
        cache_valid_time: 86400

    - name: Unifi Apt Key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 06E85760C0A52C50

    - name: Unifi Apt Repo
      apt_repository: 
        repo: deb https://www.ui.com/downloads/unifi/debian stable ubiquiti
        state: present

    - name: Mongodb Apt Key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-3.4.asc
        state: present

    - name: Mongodb Apt Repo
      apt_repository: 
        repo: deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.4 main
        state: present

    - name: get old libssl req
      command: wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb
    
    - name: Install old libssl req
      command: dpkg -i libssl1.0.0_1.0.1t-1+deb8u12_amd64.deb

    - name: Old Java for Compat KEY
      apt_key:
        url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
        state: present

    - name: Old Java for Compat Repo
      apr_repository:
        repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
        state: present
  
    - name: Install Unifi
      apt:
        pkg:
          - adoptopenjdk-8-hotspot
          - unifi
        state: latest

  