- name: Create door-bell mountpoint
  file:
    path: /mnt/door-bell
    state: directory
    mode: '0755'

- name: Mount and bind a volume
  mount:
    src: data.home.blrobinson.uk:/mnt/door-bell
    path: /mnt/door-bell
    state: mounted
    fstype: nfs4
