
---
    - name: Install Dovecot
      apt:
        name:
          - dovecot-imapd
          - dovecot-core
        state: latest
        update_cache: True
        cache_valid_time: 86400
      become: true

    - name: Install dovecot.conf
      copy:
        src: dovecot/dovecot.conf
        dest: /etc/dovecot/dovecot.conf

    - name: Copy dovecot.service
      copy:
        src: dovecot/dovecot.service
        dest: /etc/systemd/system/dovecot.service

    - name: Enable dovecot service
      ansible.builtin.service:
        name: dovecot
        state: started
        enabled: yes
