- name: Install telegraf
  apt:
    name:
      - telegraf
    state: latest
    update_cache: True
    cache_valid_time: 300
  become: true


- name: Install telegraf config
  template:
    src: 'telegraf.conf'
    dest: /etc/telegraf/telegraf.conf
  notify: reload telegraf

- name: start telegraf
  service:
    name: telegraf
    state: started
    enabled: yes