---
- name: Install Required Packages
  apt:
    pkg:
      - nginx
      - certbot

- name: Install nginx.service
  copy:
    src: nginx.service
    dest: /etc/systemd/system/nginx.service

- name: Make dir vhosts
  file:
    path: /var/www/vhosts
    state: directory
    mode: '0755'

- name: Make dir default
  file:
    path: /var/www/vhosts/default
    state: directory
    mode: '0755'

- name: Make dir wedding
  file:
    path: /var/www/vhosts/wedding
    state: directory
    mode: '0755'

- name: Make dir chick-cam
  file:
    path: /var/www/vhosts/chick-cam
    state: directory
    mode: '0755'

- name: Install Core Nginx Config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Renew certificates
  cron:
    name: renew certs
    hour: "9,13"
    minute: "0"
    job: "certbot renew --deploy-hook 'systemctl reload nginx'"

- name: Archive Grabs Folder
  cron:
    name: archive grabs folder
    hour: "9"
    minute: "0"
    weekday: "1"
    job: "rsync -a /var/www/vhosts/default/images /home/benr/grabs-archive/ && rm /var/www/vhosts/default/images/grabs/* && rm /var/www/vhosts/default/images/anirec/*"

- name: Install Nginx Configs
  vars:
    custom_config: "{{ item.custom_config }}"
    cert_name: "{{ item.cert_name }}"
    name: "{{ items.name }}"
  template:
    src: 'site.conf'
    dest: '/etc/nginx/sites-available/{{ item.name }}.conf'
    mode: 0644
  notify: reload nginx
  with_items:
    - {
        name: unifi.blrobinson.uk,
        cert_name: home_default,
        custom_config:
          '
          proxy_set_header   Host             $host;
          proxy_set_header   X-Real-IP        $remote_addr;
          proxy_set_header Referer "";
          proxy_read_timeout 300;
          proxy_connect_timeout 300;

          location /wss/ {
            proxy_pass https://unifi.home.blrobinson.uk:8443;
            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_ssl_verify off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_read_timeout 86400;
            proxy_set_header Origin "";
          }

          location / {
            proxy_ssl_verify off;
            resolver 10.0.0.12;
            proxy_http_version 1.1;
            proxy_pass https://unifi.home.blrobinson.uk:8443;
          }
          '
        }
    - {
        name: metrics.blrobinson.uk,
        cert_name: home_default,
        custom_config:
          '
          location / {
            proxy_ssl_verify off;
            proxy_http_version 1.1;
            resolver 10.0.0.12;
            proxy_pass http://metrics.home.blrobinson.uk:8086;
          }
          '
        }
    - {
        name: docker-registry.blrobinson.uk,
        cert_name: home_default,
        custom_config:
          '
          client_max_body_size 0;
          location / {
            proxy_pass http://10.0.0.100:5000/;
            proxy_http_version 1.1;
          }
          '
      }

- name: Enable nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
