---
- name: Install Required Packages
  apt:
    name:
      - nginx


- name: Install Core Nginx Config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

  
- name: Install Nginx Configs
  template: 
    src: 'site.conf'
    dest: '/etc/nginx/sites-available/{{ item.name }}.conf'
    mode: 0644
  with_items:
    - { 
        name: rivan.home.blrobinson.uk,
        custom_config:
          '
          proxy_set_header   Host             $host;
          proxy_set_header   X-Real-IP        $remote_addr;
          proxy_set_header Referer "";
          proxy_read_timeout 300;
          proxy_connect_timeout 300;	

          location /wss {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_ssl_verify off;
            proxy_pass https://10.0.0.3:8443$request_uri;
          }

          location / {
            proxy_ssl_verify off;
            proxy_pass https://10.0.0.3:8443$request_uri;
          }
          '
        }
    - {
        name: winterfell.home.blrobinson.uk,
        custom_config: 
          '
          proxy_set_header   Host             $host;
          proxy_set_header   X-Real-IP        $remote_addr;

          location / {
                  proxy_pass http://127.0.0.1:8888$request_uri;
          }
          '
    }
    - { 
      name: wedding.blrobinson.uk,
      custom_config: 
        '
        location / {
          index index.html;
          root /var/www/vhosts/wedding;
          try_files $uri $uri/index.html =404;
        }
        '
      }
