---
- name: Install Common Tools
  apt:
    name:
      - vim
      - htop
      - dnsutils
      - traceroute
      - rsync
      - curl
      - lsof
      - sl
      - tree
      - ack
      - zip
      - unzip
      - strace
      - screen
      - mtr
    state: latest
    update_cache: True
    cache_valid_time: 86400
  become: true

