---
- name: Copy Influx Data repo
  copy:
    src: apt/influxdata.list
    dest: /etc/apt/sources.list.d/influxdata.list

- name: Copy Influx Key
  copy:
    src: apt/influxdb.key
    dest: /etc/apt
  register: influxkey

- name: Install Influx Key
  shell: echo '23a1c8836f0afc5ed24e0486339d7cc8f6790b83886c4c96995b88a061c5bb5d /etc/apt/influxdb.key' | sha256sum -c && cat /etc/apt/influxdb.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/influxdb.gpg > /dev/null
  become: true
  when: influxkey.changed

- name: Install Common Tools
  apt:
    name:
      - vim
      - htop
      - dnsutils
      - traceroute
      - rsync
      - curl
      - lsof
      - sl
      - tree
      - ack
      - zip
      - unzip
      - strace
      - screen
      - mtr
      - unattended-upgrades
      - apt-listchanges
      - mailutils
      - postfix
      - ifenslave
    state: latest
    update_cache: True
    cache_valid_time: 300
  become: true

- name: Copy Apt auto-update
  copy:
    src: apt/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades

- name: Copy Apt unattended
  copy:
    src: apt/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
