---
    - name: Set interfaces file
      template: 
        src: interfaces
        dest: /etc/network/interfaces

    - name: Set resolv.conf
      copy:
        src: network/resolv.conf
        dest: /etc/resolv.conf
