- name: download influxdb
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.7-amd64.deb
    dest: /tmp/influxdb.deb

- name: Install influxdb .deb package
  apt:
    deb: /tmp/influxdb.deb

- name: start influxdb
  service:
    name: influxdb
    state: started
    enabled: yes