- name: Install influxdb
  apt:
    name:
      - influxdb2
    state: latest
    update_cache: True
    cache_valid_time: 300
  become: true

- name: start influxdb
  service:
    name: influxdb
    state: started
    enabled: yes