---
- name: Install Hypervisor Tools
  apt:
    name:
      - qemu-system
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-utils
    state: latest
    update_cache: True
    cache_valid_time: 300
    install_recommends: False
  become: true

- name: adding 'benr' to group libvirt
  user:
    name: benr
    groups: libvirt
    append: yes